export const siteConfig = {
  name: "Sangi Hospital",
  legalName: "Sangi Hospital",
  tagline: "Trusted Multi-Speciality Healthcare Network",
  description:
    "Sangi Hospital is a trusted multi-speciality healthcare provider with hospitals across Uttar Pradesh. Book appointments with expert doctors for cardiology, neurology, gynecology, emergency care, and more.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.sangihospital.com",
  locale: "en_IN",
  region: "Uttar Pradesh, India",
  phone: "+91 931 121 2090",
  phoneTel: "+919311212090",
  email: "info@sangihospital.com",
  social: {
    facebook: "https://www.facebook.com/sangihospital",
    linkedin: "https://www.linkedin.com/in/sangihospital/",
    instagram: "https://www.instagram.com/sangihospital",
  },
  defaultOgImage: "/assets/images/home/hero_bg_1.jpeg",
  keywords: [
    "Sangi Hospital",
    "hospital in Uttar Pradesh",
    "multi-speciality hospital",
    "book doctor appointment",
    "Aligarh hospital",
    "Baghpat hospital",
    "Mainpuri hospital",
    "emergency care",
    "cardiology",
    "neurology",
    "gynecology",
    "dental care",
  ],
  locations: [
    "Aligarh",
    "Baghpat", 
    "Mainpuri",
    "Shikohabad",
    "Raya",
    "Laxmi Nagar",
  ],
  specialties: [
    "Emergency Medicine",
    "Cardiology",
    "Neurology",
    "Gynecology",
    "Dental Care",
    "Psychiatry",
    "Radiology",
    "Pathology",
  ],
} as const;
